#!/bin/sh

# Check for NOCOMMIT in code
FOUND=0
for FILE in `git diff --name-only --staged`; do
    if [ "$FILE" != "githooks/pre-commit" ]; then
        grep 'NOCOMMIT' $FILE 2>&1 >/dev/null
        if [ $? -eq 0 ]; then
            echo 'NOCOMMIT in' $FILE
            FOUND=1
        fi
    fi
done

if [ $FOUND -eq 1 ]; then
    echo "\033[0;31mCommit aborted!\033[0m"
    exit 1
fi

ROOT=`dirname $GIT_DIR`
BUILD_NUMBER=`git describe | awk -F'-' '{print $2}'`
BUILD_NUMBER=$((BUILD_NUMBER+1))
$ROOT/tasks/updateBuildNumber $BUILD_NUMBER
git add $ROOT/src/cordova/cordovaconfig.xml


